rbacEnabled: true
replicaCount: 1
image:
  repository: docker.io/nmaupu/kube-ingwatcher
  tag: "1.6"
  pullPolicy: IfNotPresent

target:
  addr: rproxy-pub.example.com
  port: 6565
ingressSenderArgs:
  - ingressSender
  - -l
  - lb-type=pub
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 20m
    memory: 32Mi
