{{- if .Values.rbacEnabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "traefik.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "traefik.fullname" . }}-cr
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "traefik.fullname" . }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "traefik.fullname" . }}-cr
subjects:
- kind: ServiceAccount
  name: {{ template "traefik.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
