{{ $fullname := include "traefik.fullname" . }}
{{- range $key, $val := .Values.services }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $fullname }}-svc-{{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    k8s-app: {{ $fullname }}
  type: {{ $val.type }}
  ports:
    - protocol: TCP
      port: {{ $val.port }}
  {{- if eq $val.type "nodePort" }}
      nodePort: {{ $val.targetPort }}
  {{- else }}
      targetPort: {{ $val.targetPort }}
  {{- end }}
{{- end }}
