apiVersion: v2
name: pv-snapshotter
description: A persistent volume snapshotter with auto cleaning feature (use google persistent disk CSI driver)
type: application

version: 0.1.0
appVersion: "1.0.0"
