{{- $redisVersion := "v0.0.1" -}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "appFullName" . }}-redis-deploy
  labels:
    k8s-app: {{ template "appFullName" . }}-redis
    version: {{ $redisVersion }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: {{ template "appFullName" . }}-redis
    version: {{ $redisVersion }}
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}:{{ .Values.redis.tag }}
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 6379
        resources:
{{ toYaml .Values.redis.resources | indent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "appFullName" . }}-redis-svc
  labels:
    k8s-app: {{ template "appFullName" . }}-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    k8s-app: {{ template "appFullName" . }}-redis
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
