{{- if .Values.rbacEnabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-ingwatcher.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "kube-ingwatcher.fullname" . }}-cr
rules:
- apiGroups:
    - "extensions"
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "kube-ingwatcher.fullname" . }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-ingwatcher.fullname" . }}-cr
subjects:
- kind: ServiceAccount
  name: {{ template "kube-ingwatcher.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
