---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pv-snapshotter.fullname" . }}
  labels:
    {{- include "pv-snapshotter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs: ["get", "list", "create", "delete"]
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["get"]
