apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dolibarr.fullname" . }}
  labels:
    app: {{ template "dolibarr.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  db-username: {{ .Values.conf.db_username | b64enc | quote }}
  db-password: {{ .Values.conf.db_password | b64enc | quote }}
  cookie-key: {{ .Values.conf.cookie_key | b64enc | quote }}
