replicaCount: 2

image:
  repository: traefik
  tag: 1.5.3-alpine
  pullPolicy: IfNotPresent
  args:
    - --web
    - --kubernetes
    - --kubernetes.labelselector=lb-type=priv

services:
  web:
    type: NodePort
    port: 80
    targetPort: 30080
  admin:
    type: ClusterIP
    port: 8080
    targetPort: 8080

ingress:
  enabled: true
  hosts:
    - traefik-priv.priv.fossar.net
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    lb-type: priv

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
