apiVersion: v1
kind: Secret
metadata:
  name: {{ template "compte.fullname" . }}
  labels:
    app: {{ template "compte.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  db-user: {{ .Values.db.user | b64enc | quote }}
  db-password: {{ .Values.db.password | b64enc | quote }}
