---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: gke-vol-snapshot
parameters:
  storage-locations: europe-west1
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
