---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-bot.fullname" . }}
  labels: {{- include "telegram-bot.labels" . | nindent 4 }}
data:
  config.yaml: {{- toYaml .Values.botConfig | b64enc | nindent 4 }}
